name: test

# on:  
#   workflow_run:
#     workflows: [build]
#     types:
#       - success
on:
  pull_request:
    # branches: [ master ]
  workflow_dispatch:


env:
  ACCOUNT: ${{ github.repository_owner }}


jobs:

  # ----------- TESTS ----------- #

  unit-test:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/mapattacker/github-workflow-sample
      credentials:
          username: $ACCOUNT
          password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: run tests
        run: pytest --cov=project/ tests/unit_tests/ -v

        
  # ----------- SECURITY SCANS ----------- #

  dependency-review:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/dependency-review-action@v4
        with:
          deny-licenses: |
            # GPL-3.0
            GPL-2.0
            AGPL-3.0
            AGPL-1.0
          fail-on-severity: low
          fail-on-scopes: runtime
          comment-summary-in-pr: true
